# Travis-CI Build for Hangfire
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.
language: c

# Make sure build dependencies are installed.
install:
 - sudo add-apt-repository -y ppa:directhex/monoxide
 - sudo apt-get update -qq
 - sudo apt-get install -qq mono-devel mono-gmcs cli-common-dev
 - mozroots --import --sync
 - travis_retry mono --runtime=v4.0 .nuget/NuGet.exe install .nuget/packages.config -OutputDirectory packages
 - travis_retry mono --runtime=v4.0 .nuget/NuGet.exe restore Hangfire.Mono.sln
cache: apt

services:
  - redis-server
  - rabbitmq

# Run the build script
script:
 - ./build.sh

# Only watch the master branch.
branches:
 only:
   - master
   - dev
