# Travis-CI Build for Hangfire
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.
language: c

# Make sure build dependencies are installed.
install:
 - sudo add-apt-repository -y ppa:directhex/monoxide
 - sudo apt-get update -qq
 - sudo apt-get install -qq mono-devel mono-gmcs cli-common-dev
 - mozroots --import --sync
cache: apt

services:
  - redis-server
  - rabbitmq

# Run the build script
before_script: 
 - mono  --runtime=v4.0 ./.nuget/nuget.exe install .nuget/packages.config -OutputDirectory packages
 - mono  --runtime=v4.0 ./.nuget/nuget.exe restore Hangfire.Mono.sln
script:
 - ./build.sh
after_script:
 - mono --runtime=v4.0 ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.x86.exe tests/Hangfire.Core.Tests/bin/Debug/Hangfire.Core.Tests.dll
 - mono --runtime=v4.0 ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.x86.exe tests/Hangfire.SqlServer.RabbitMq.Tests/bin/Debug/Hangfire.SqlServer.RabbitMq.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
   - dev
