# Travis-CI Build for Hangfire
# see travis-ci.org for details

language: csharp
sudo: required

# Make sure build dependencies are installed.
install:
 - travis_retry mono .nuget/nuget.exe install .nuget/packages.config -OutputDirectory packages
 - travis_retry mono .nuget/nuget.exe restore Hangfire.Mono.sln
 
cache: 
 - apt
 - directories:
   - packages

# Run the build script
script:
 - xbuild /p:Configuration=Release /verbosity:minimal Hangfire.Mono.sln
 - mono ./packages/xunit.runner.console.2.2.0-beta2-build3300/tools/xunit.console.exe ./tests/Hangfire.Core.Tests/bin/Release/Hangfire.Core.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
   - dev
