# Travis-CI Build for Hangfire
# see travis-ci.org for details

language: csharp
sudo: required
dist: trusty
osx_image: xcode7.2

mono: none
dotnet: 1.0.0-preview2-003121

os:  
  - linux
  - osx
  
# Only watch the master branch.
branches:
  only:
    - master
    - dev

# Make sure build dependencies are installed.
install:
  - travis_retry dotnet restore

# Run the build script
script:
  - dotnet test tests/Hangfire.Core.Tests
 
# Tests on Mono disabled – waiting for https://github.com/NuGet/Home/issues/3085
# Also waiting for nuget package to be updated to 2.12
# - travis_retry mono .nuget/NuGet.exe install .nuget/packages.config -OutputDirectory packages
# - travis_retry mono .nuget/NuGet.exe install .
# - xbuild /p:Configuration=Release /verbosity:minimal Hangfire.Mono.sln
# - mono ./packages/xunit.runner.console.2.2.0-beta2-build3300/tools/xunit.console.exe ./tests/Hangfire.Core.Tests/bin/Release/Hangfire.Core.Tests.dll
